Add mul and matmul documentation
pypose/pypose pull request #115
Opened 2022-08-20 06:46 UTC by AAkashyap1

2022-08-20 16:52 UTC, wang-chen requested changes
I think you are misuse some symbols:
1. `matmul` only refers to the `@` operation, `mul` refers to the `*` operation.
2. in equations, `x` should only refer to `@`.
You also need to clearly discuss the different cases.

For example,
- [x] LieTensor * scalar
- [x] LieTensor * Tensor (last dimension is 3)
- [x] LieTensor * Tensor (last dimension is 4)
- [ ] LieTensor * LieTensor
- [ ] LieTensor @ LieTensor

2022-08-20 16:52 UTC, wang-chen commented on pypose/lietensor/basics.py
> +        input (:obj:`LieTensor`) the input LieTensor (Lie Group or Lie Algebra).
format not correct, you need `:` between type and its explanation.
for example:
```
input (:obj:`LieTensor`): the input LieTensor (Lie Group or Lie Algebra).
```

2022-08-20 16:52 UTC, wang-chen commented on pypose/lietensor/basics.py
> +        the product with the same type as ``other``
You need a type for returns. For example,
```
Tensor/LieTensor: the product with the same type as ``other``.
```
Please refer to other docs for function return.

2022-08-20 16:52 UTC, wang-chen commented on pypose/lietensor/basics.py
> +    :obj:`LieTensor` @ :obj:`Tensor` -> :obj:`Tensor` (group action)
You need to clearly define different situations, refer to the doc of [Exp](https://pypose.org/docs/main/generated/pypose.Exp/)

2022-08-20 17:12 UTC, wang-chen commented on pypose/lietensor/basics.py
> +        input (:obj:`LieTensor`) the input LieTensor (Lie Group or Lie Algebra).
if some of the cases, you may also let the readers refer to doc of `Act`: https://pypose.org/docs/main/generated/pypose.Act/

2022-08-25 01:03 UTC, wang-chen commented on pypose/lietensor/basics.py
> +        :math:`(\bm{x} \ast \bm{a})_{t}`.
This is not a doc, you need to give explicit equation.

2022-08-29 02:39 UTC, wang-chen commented
I just made several changes, please have a look @AAkashyap1 , you also need to add 3 more examples for `RxSO3`, `SE3`, and `Sim3`.

2022-08-29 23:08 UTC, AAkashyap1 commented
@wang-chen, I added in the examples and your changes looked good.

2022-08-31 20:35 UTC, wang-chen approved these changes

2022-08-31 20:47 UTC, merged