Feature/multi error
pypose/pypose pull request #243
Opened 2023-05-19 02:41 UTC by xukuanHIT

#148

2023-05-26 03:55 UTC, wang-chen requested changes

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +            target = [None for i in range(len(output))] if target is None else target
how about
```python
target = [None] * len(output) if target is None else target
```

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +            return tuple([self.residual(output[i], target[i]) for i in range(len(output))])
how about
```python
return tuple([self.residual(out, target[i]) for i, out in enumerate(output)])
```

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +    def residuals(self, output, target):
how about change args name to `outputs` and `targets`

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +
it seems that this function is not used, remove it.

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +        return sum(residuals)
how about change `residual_list` to `residuals`

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +                weight_diag += [w for i in range(int(ni))]
do you mean
```
weight_diag += [w] * int(ni)
```

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +    def normalize_R_weight(self, R, weight=None):
is this function identical to both GN and LM? if yes, how about moving it to the class of `RobustModel`, so that it only appear once?

2023-05-26 03:55 UTC, wang-chen commented on pypose/optim/optimizer.py
> +    def normalize_R_weight(self, R, weight=None):
I also need a meeting with you to explain the math background of this function.

2023-05-30 08:26 UTC, xukuanHIT commented on pypose/optim/optimizer.py
>          assert torch.is_floating_point(output), "model output have to be float type."
OK

2023-05-30 08:26 UTC, xukuanHIT commented on pypose/optim/optimizer.py
> +            target = [None for i in range(len(output))] if target is None else target
OK

2023-05-30 08:31 UTC, xukuanHIT commented on pypose/optim/optimizer.py
> +            return tuple([self.residual(output[i], target[i]) for i in range(len(output))])
ok

2023-06-11 09:08 UTC, closed without merging