Evaluations for the trajectory including APE and RPE
pypose/pypose pull request #316
Opened 2023-12-11 13:21 UTC by Chensiyu00

The pull request first introduces two parts in pypose direction.

1. geometry.py
    In this part, a function named **svdstf()** is introduced.  Different from **svdtf()**, **svdstf()** can get the Sim(3) optimization to align two sets of points.

2. metric.py
    The basic process for evaluating the APE is: 
           1. Synchronize the estimated trajectories using the timestamps, 
           2. Align two trajectories using SE(3) or Sim(3) or None which is according to the setting given by users, 
           3. Calculate the errors ('translation', 'rotation' and etc.) based on requirements
    
     The basic process for evaluating the RPE is: 
           1. Synchronize the estimated trajectories using the timestamps, 
           2. Align two trajectories using SE(3) or Sim(3) or None which is according to the setting given by users,
           3. Get the pose pairs to calculate based on frame or translation.
           4. Calculate the errors ('translation', 'rotation' and etc.) based on requirements

The robustness evalution will be realized later.

2024-10-11 13:09 UTC, ericzzj1989 commented on pypose/function/geometry.py
> +def svdstf(source: torch.Tensor, target: torch.Tensor, with_scale: bool=True):
viewed

2024-10-16 16:11 UTC, wang-chen requested changes

2024-10-18 10:44 UTC, ericzzj1989 commented on tests/function/test_metric.py
> +from pypose.function.metric import compute_APE, compute_RPE, StampedSE3
Change `pypose.function.metric.compute_APE, compute_RPE, StampedSE3` to `pypose.function.ape` and `pypose.function.rpe`, not `pypose.metric.ape` and `pypose.metric.rpe`

2025-01-10 19:38 UTC, wang-chen approved these changes

2025-01-10 19:40 UTC, merged